### ISSUE TITLE
Energia code for fuzzy speed controller on C language

### ISSUE THREAD

**Issue by DilHem** [zerokol/eFLL#16]
Hey All,
Its Urgent,

Can anyone provide me C language code for fuzzy logic speed controller. I'm doing this Using ENERGIA interface.
I'm taking my inputs using a ultrasonic sensor and after fuzzy methods the outputs are taken by DC motors as their inputs and then after they are going to control the speed or the rotation speed of DC motor.

Thank You

Energia code for fuzzy speed controller on C language

**Comment by zerokol** [comment]
I guess I have a code that may help you. Go to my github profile, find my email address and send my one email.
