### ISSUE TITLE
Fuzzy PID Controller Example?

### ISSUE THREAD

**Issue by edgsc** [zerokol/eFLL#17]
Hi and thanks for your attention!

I've seen the examples, but couldn't figure out if it's possible to use this library with Brett's Beauregard's PID library (or any PID).
Would FuzzyOutputs be Kp, Ki, Kd?
3 outputs and 2 inputs (setpoint and measured variable)?

Thanks!

**Comment by zerokol** [comment]
Yes, you can build a Fuzzy system with 2 inputs and 3 outputs, the advanced-example show how to build a system with 2 outputs.
