### ISSUE TITLE
Floating number of input

### ISSUE THREAD

**Issue by coreco46** [zerokol/eFLL#19]
Hi, I have tried the code from example and it worked fine. But I have some issues found by changing the input to a pair of floating numbers. it did not give result as its proper calculation of the Fuzzy rule. I try to change the data type of the inputs Int --> float, but it did not work.
How can I use the floating number inputs?

Next issue was, I try to modify the example code to 2 inputs (5 memberships functions each, which give 25 fuzzy rules) and 1 output (also has 5 membership functions), the code I attached below. I have manually tried the code by pairs of different inputs. but some pair of input numbers can not give any result. I dont know why.

Please, can somebody help me?

Thanks in advance

[FLC_2input_5stage_e_de.zip](https://github.com/zerokol/eFLL/files/3465657/FLC_2input_5stage_e_de.zip)

**Comment by zerokol** [comment]
Hey, it should accept float numbers as input! Is this attached code the same of the first issue?

**Comment by coreco46** [comment]
Hi, sorry for the late reply. It did can be input with float number, but gives wrong calculation on output. I compared it to the Fuzzy on Matlab Toolbox, the floating number gave output calculation as if it being rounded as integer. 

The code attached has same issue, but I have another more important issue that not all integer pair of input give result on that code. for example pair of inputs [1,3] as attached

**Comment by zerokol** [comment]
Can you provide a bit more of details, please.
