### ISSUE TITLE
Problem with reach maximal defined value from output set - arduino_simple_sample.ino and not only

### ISSUE THREAD

**Issue by maxprog** [zerokol/eFLL#20]
Hello,
I can't reach max defined value from output rule - both in my or Your codes placed on github. 
For Instance in your sample:  arduino_simple_sample.ino please change following line to:
  int input = 80;
always will be returned 40 instead of 50. Maximum value is 50 in output set:
FuzzySet *fast = new FuzzySet(30, 40, 40, 50);
but  and I can't reach max defined value.
Maybe mistake is on my side or in library
<img width="1251" alt="Screenshot 2020-01-20 at 08 48 02" src="https://user-images.githubusercontent.com/13249768/72707980-01b9a980-3b62-11ea-9350-d6fb5a78c4a6.png">
?

**Comment by maxprog** [comment]
I see that also for input value 79 is returned 40
<img width="1259" alt="Screenshot 2020-01-20 at 09 07 30" src="https://user-images.githubusercontent.com/13249768/72709118-84dbff00-3b64-11ea-841b-b0b6a85a0bd8.png">

**Comment by maxprog** [comment]
Problem Solved

**Comment by zerokol** [comment]
Sorry, for late response. May you explain what was wrong?
