### ISSUE TITLE
3 ouput

### ISSUE THREAD

**Issue by murtadhodaf** [zerokol/eFLL#26]
is this library allow to 3 output on fuzzy ?

**Comment by zerokol** [comment]
Yes, the library has no limitations in numbers of inputs, rules and outputs... the limitation is the hardware.

**Comment by murtadhodaf** [comment]
thx for helping me

**Comment by murtadhodaf** [comment]
if the ouput more than 2 what is the syntx for it ? is just adding the output or using joinWithAND

**Comment by zerokol** [comment]
Not exactly, https://github.com/zerokol/eFLL/blob/master/examples/general_advanced_sample/general_advanced_sample.cpp take a look in this example. It uses two outputs, to create a new output you will need to set new FuzzyOutput, with its FuzzySet s and then create some FuzzyRuleConsequent with its Rules. =)

**Comment by murtadhodaf** [comment]
oooh i got it just add the output after FuzzyRuleConsequent. is it like this ? 

	`FuzzyRuleAntecedent *FP_N1 = new FuzzyRuleAntecedent();
	FP_N1->joinWithAND(FP, N1);

	FuzzyRuleConsequent *SEDANG1_SEBENTAR3_2 = new FuzzyRuleConsequent();
	SEDANG1_SEDANG3_2->addOutput(SEDANG1);
	SEDANG1_SEDANG3_2->addOutput(SEBENTAR3);
	SEDANG1_SEDANG3_2->addOutput(ZERO2);

	FuzzyRule *fuzzyRule41 = new FuzzyRule(41, FP_N1, SEDANG1_SEBENTAR3_2);
	fuzzy->addFuzzyRule(fuzzyRule41);`

**Comment by zerokol** [comment]
yes, basically, it you have a FuzzyOutpput, it works.

**Comment by murtadhodaf** [comment]
thx for helping me is it can be to close or not ?

**Comment by zerokol** [comment]
Graeat!
