### ISSUE TITLE
Does not work on arduino_esp32

### ISSUE THREAD

**Issue by ilijamr** [zerokol/eFLL#27]
Hello, fantastic library, but cannot get it to work on ESP32, it is restarting. I am using simple example and will try to isolate problem since it is compiling in order.

**Comment by ilijamr** [comment]
float output = fuzzy->defuzzify(1) causes the crash.

**Comment by zerokol** [comment]
Hey, not sure, I never tested it on multitasking env, can you provide me more info, I want to try it.

**Comment by ilijamr** [comment]
I will send you the code for ESP32 and Arduino Uno, just need your e-mail.

**Comment by zerokol** [comment]
Hey @ilijamr I just pushed a new release, tag name: 1.3.0, I fixed a runtime error, may you check if it was the issue?

**Comment by ilijamr** [comment]
Ok, I will, and then I will let you know if the problem persists.

**Comment by zerokol** [comment]
Thanks, Any way, my email is: aj.alves@zerokol.com

**Comment by ilijamr** [comment]
I don't know what you did but it works now :) Thanks.

**Comment by zerokol** [comment]
Great! Thanks for report!
