### ISSUE TITLE
Fuzzy Rule not fired

### ISSUE THREAD

**Issue by Bingsitfx** [zerokol/eFLL#29]
i have 2 fuzzies
first fuzzy is running correctly, but the second fuzzy sometimes Rule not fired.
![image](https://user-images.githubusercontent.com/75128380/124347812-b178bf00-dc10-11eb-98a7-d53ce2d61024.png)

**Comment by zerokol** [comment]
Please, test again with version 1.4.1

**Comment by Bingsitfx** [comment]
> Please, test again with version 1.4.1

Okey tomorrow i will test this version. If I may know, what caused this defuzzy result is "0" ?
Thankyou

**Comment by zerokol** [comment]
> > Please, test again with version 1.4.1
> 
> Okey tomorrow i will test this version. If I may know, what caused this defuzzy result is "0" ?
> Thankyou

I found some strange logic in the process of defuzzification, now it is much more accurate on the edge cases
