### ISSUE TITLE
Help please, fuzzy->defuzzify always showing 0

### ISSUE THREAD

**Issue by andytkomskt** [zerokol/eFLL#33]
.

**Comment by Diogo-Gomes** [comment]
Hi!

I'm having the same problem, did you get any progress?

**Comment by andytkomskt** [comment]
My project was finished 2 years ago. But you can check the system requirement of your microcontroller and make sure you don't create function you use repeatedly on Antecedent. Like a

FuzzyRuleAntecedent *ifCoolBasa = new FuzzyRuleAntecedent();
ifCoolBasa->joinWithAND(Cool, Basa);

Don't create function like this one, then you call in future repeatedly
FuzzyRuleAntecedent *ifCool = new FuzzyRuleAntecedent();

Still stuck? Send me your code

**Comment by Diogo-Gomes** [comment]
Thanks for the quick response @andytkomskt.

I solved the problem by reducing the number of rules. It was really a hardware limitation of my microcontroller.
