### ISSUE TITLE
How do you generate FuzzyInputs?

### ISSUE THREAD

**Issue by jpuriol** [zerokol/eFLL#6]
I have learned about Fuzzy Logic from this article: https://archive.org/details/ControlPIDFuzzyLogic-Fuzzy-LogicSystemSolvesControlProblemOCR.

I look a this code from the simple general example and I'm not a 100% sure what is doing:
```
// Criando o FuzzyInput distancia
FuzzyInput* distance = new FuzzyInput(1);
// Criando os FuzzySet que compoem o FuzzyInput distancia 
FuzzySet* small = new FuzzySet(0, 20, 20, 40); // Distancia pequena
distance->addFuzzySet(small); // Adicionando o FuzzySet small em distance
FuzzySet* safe = new FuzzySet(30, 50, 50, 70); // Distancia segura
distance->addFuzzySet(safe); // Adicionando o FuzzySet safe em distance
FuzzySet* big = new FuzzySet(60, 80, 80, 80); // Distancia grande
distance->addFuzzySet(big); // Adicionando o FuzzySet big em distance
```

My problem comes from the constructor of the `FuzzySet(float a, float b, float c, float d)`. Could you help me understand what  `FuzzySet* small = new FuzzySet(0, 20, 20, 40)`  exactly means?

**Comment by zerokol** [comment]
It is just a configuration to set the pertinence function function; Depending on the parameters, it shuld be triangular, trapezoidal or singleton

**Comment by jpuriol** [comment]
How will you make it triangular? What shape has the example?

**Comment by jpuriol** [comment]
Never mind, @zerokol , I found on the documentation on english on your[website](http://www.zerokol.com/2012/09/arduinofuzzy-fuzzy-library-for-arduino.html). Thank you!
