### ISSUE TITLE
The Library works up to the 4th Rule

### ISSUE THREAD

**Issue by ezonatto** [zerokol/eFLL#7]
Hello,
The library works very well up to the 4th rule. When the 5th is added the code stops working. No errors have been appeared during compiling or uploading. Nothing appear in the Monitor Display but if I delete all rules leaving only 4 rules the code works again.

**Comment by zerokol** [comment]
It is weird! There is no limitation of this kind in the library. Can you convert the arduino sketch in a simple cpp program? It is easy, look at the example folder and you will find a sample!

**Comment by zerokol** [comment]
I will close for inactivity.
